ver: 3
prefix:
  - "!"
  - "！"
  - "."
BotID: 2139645544
BotNick: "人工制杖"
GroupID:
  - 1138627074
  - 682204087
  - 826444726
  - 907187763
MainGroup: 1138627074
ChatGPT-Token: "eyJhbGciOiJkaXIiLCJlbmMiOiJBMjU2R0NNIn0..Jp-PdVb6vjX9GL-E.cg_CehCAg1unvXZrGX4JKoHyS5KJb3xGgk6EOt1flmeaByeomOMbSLfHg7gdJDw-hfalReYXwkJ84wcp83kMqWEqO2nGSzX8zcj1q4bLPRaajJccNKiwheGyj7o0MHu8VZZqAKQcFF6YCjEmTQ-r_yN16bWBs4BZKOvUp-YniE6rdO8NS8DjDW4lNUKeNY-7OIXY0D8i982c-3h41v7uq8UQ1UsNkTiwlwZI2tsxPwu8n7gSAt8fqjc0aBDxwAk--UmMPbJLZaw05mXggLpmEqHGtcVvl6okFH7e6z_07hHThHn7PR_QoFNTR8NsZqNnsrfinOPgFqVLZLwM0SsP6Utgpp-xSETW4YDzGvgRqjUUezkhHkI9qdoC7n8KJ5bjgNyRYOB6Vl0cHzFQ8s-rT9N2DW7mEJDmmDCdWwuBBXOai3vp5tOT1ZBFv9WQf4L_4axgUy7iuhqF6iKoKOtpOS5p3puQ5C2g8HIPWncWO2ZuMjASPurDIG0fCCgTVYdjZJYmytisjvz3kIJTZkIoOpWrlzGay39zagud04Ozce6Gh5-fLK3UXqZEr4aWu6sJ4u1KMXcxZ2eRn4mt23TKCvG6RLsnhlucGoznmsymR1WLGa9HPSWsl0MrgrySfMukKr62lKjPKu6ZrHoHdyq9ILeyOKre3PluMDmP85CegzU09VUFC8MCiNggJItf5xahb2UhQIKVF_95hkgCGoiEXcigm_m1PCd8AZyshXXBrwi03cbrkIvqqpVSBcMaim5QBf_r_b9M3RjsLjIUK6LhZtL74pvaJblz1b_UZW-_xy_YW3dOHGZl7s4z-2TwA8D1D81OOj4L-XILaLzC5Bv-adEtAMoLNgmRk9jdieJxmGWPw6AYhnES_sNdNoCLiDba3CB3kAyrz-c6BCuBq6C5pOnRVcEsUSY55C8mEp9JOlT4dj0le3JJA_tvhA8tn5ZUGvCoS8U2MxAk4x7wY0oFbjLMmqZzUjjaiUTQWrVn46nwZkygItNr5Xd8XTjYSQPXucx932g3LV9rpHKIkJ7GXQDej05_zjj6ZYc-ZvHpVy55nue9rdAq9LUifqQylQXtosWtMJ9qP1Mmc4iYtF_ZuzaznTlCNDuOmM7QvUFwNm0qaknDv0CMgCOnMPCG4pKi0Ilnd-Iim_nQAShhM6yRHyeDZHaHAfX4oj-mLNt7zKoFgdfpTb85TPO632ePvBzNL5SeJBeMmUgzCGMovXlMkmsgj2Ocby0QdxoWTmrHgO_jUQjhE0M4ypfG_Vp4doJ_uInBbYH_ArKMe8yJkGvQO1RVXg_ylI09fbwxiqxir8C9Ltvzitb8GseiebO1ua-5ZNTgshNDmb-H7tf0emGP_0owR-2DnUSDxkH-4oOrCEFKWcX7ZqvQJ0D2xSyDW52f78rjZ5ceZcokJ51ySEwTsiyHlFhvjnHYA7q0fFcyEsUPM6bc8c5kIc1uOhW9cjCbQnckSaxQpDMRrQO1zzu7FVFt_4E5oJ3yBz63XQI8jo85Os6AqMNxCDgpJfLYwm8HJs7dGMzzIBRUJnSHQHiQtarc4i9AmOXuvxWsD3_7mZR9m4yDkT3YbIlW62BXswv90deJ8kEJgPXTSBHfBSBL0ApJUPo2OxzjwnVKUQjyMaHFQdn-JyB7Wyw7d9m_BWsHM-a50mz3D5oFJxob6qb5f8iwF0VN0bfLn-gWuEuGWc4pdzB7jpA5ZNp6evQTJLdnE8bY42cRFyVfZH-v1Cn0eBAnU2_ntKV9QsKYqcBmBfdHD7TQ0vlBE6Zo5FAEepFAnWm2tRzfhVEnl8EXfyqrnK_0FGhW9fOx6K3zo4g25doq7WGA8tLeW15Bs_3Bb6Nbx2vvsZl_AwWtezgOa0_Z-S09spoET_ExbDZCQuw-MhOcWdDu3-iXI0hvl9Cvjd5rl1XG9ISUCTxdg_81NmzA81XCk3YCg6XtW0AHn1ZTfL7ZN4sPNVEV_8_wWaxs7UJVcs8PTEAQr0O1I9ybuJ-jgT96KgRQ6qVN1goBoROF031kQV6TTM2RhTAnY0oxxukDirOL5Tb6-LCq-IFnFWYWFPKpVhEfr_BdC1g0jpt9DQxTuMt1l0zfCEi2xw4Uk1O8WJzWhfTQROFsEGHvN6_eArKMdmFsRyZW-tVGO3IKj1xrRKmhwZtOa3a8onpTQkwiVaLkO5rcmdMy6LZNwe2uM9Sy4PPJuNA4v8FpGAb2bPEu2UhGyDqujoNfawQ8h1Lo-TVpZf1qnlSEYYzerxGGRY7My9nSLybasXxKsCktWlqCTYRt3XtrjI47XD16FRqOMk4SCDojproy8VYHlDtwbj7Mkkkqgo9sJJxiNYkYr1LUgE5HAfKxnFMZsuKfrVMTBANd1BEbroxpKA.ZYIRE25Ahc259_P8-xx35g"
NumMessage:
  - num: 0
    text:
      - "当前无人在线"
      - "服务器现在没有人在线哦"
      - "没人诶..."
  - num: 1
    text:
      - "{0} 正在独自遨游世界"
      - "{0} 正在独自一人游玩"
  - num: 2
    text:
      - "{0} 和 {1} 正在体验二人世界"
noWhiteKick: |-
  &6米&f客
  &7-------------------
  &f此ID还没有白名单呢
  &f您的绑定验证码是&6%verify%
  &f加入我们的QQ群&a1138627074&f并在群里发送
  &6.bind %verify%
  &f即可获得白名单
  &f验证码在&c10分钟&f后过期
  &7-------------------
join: |-
  欢迎加入米客服务器
  您需要进入服务器并根据提示获取服务器白名单
  求求您看看公告吧
  公告能解决您的大部分问题
chat:
  prefix:
    - "#"
    - "＃"
  format:
    # 这行支持papi
    server-to-qq: "$[player]: $[message]"
admin:
  - 2704804982
  - 1802732019
  - 1665807109
  - 65504318
  - 2276283971
  - 2076911801
  - 3589711038
  - 752779588
recall:
  enable: true
  mute:
    # 单位: 次数
    value: 3
    # 单位: 秒
    time: 120
  text:
    # 英文请用小写
    - "习大大"
    - "xjp"
    - "习近平"
    - "毛泽东"
    - "邓小平"
    - "马克思"
    - "社会主义"
    - "主席"
    - "党"
    - "政治"
    - "中共"
    - "共产"
    - "台湾"
    - "起义"
    - "压迫"
    - "自由"
    - "独裁"
    - "人大"
    - "天安门"
    - "统治"
    - "反抗"
    - "复辟"
    - "帝制"
    - "袁世凯"
    - "专制"
    - "翻墙"
    - "vpn"
    - "gfw"
    - "言论"
    - "人权"
    - "罢课"
    - "罢工"
