ver: 3
prefix:
  - "!"
  - "！"
  - "."
BotID: 2139645544
BotNick: "人工制杖"
GroupID:
  - 1138627074
  - 682204087
  - 826444726
  - 907187763
MainGroup: 1138627074
ChatGPT-Token: ""
NumMessage:
  - num: 0
    text:
      - "当前无人在线"
  - num: 1
    text:
      - "{0} 正在独自遨游世界"
      - "{0} 正在独自一人游玩"
  - num: 2
    text: 
      - "{0} 和 {1} 正在体验二人世界"
noWhiteKick: |-
  &6米&f客
  &7-------------------
  &f此ID还没有白名单呢
  &f您的绑定验证码是&6%verify%
  &f加入我们的QQ群&a1138627074&f并在群里发送
  &6.bind %verify%
  &f即可获得白名单
  &f验证码在&c10分钟&f后过期
  &7-------------------
join: |-
  欢迎加入米客服务器
  您需要进入服务器并根据提示获取服务器白名单
  求求您看看公告吧
  公告能解决您的大部分问题
chat:
  prefix:
    - "#"
    - "＃"
  format:
    # 这行支持papi
    server-to-qq: "$[player]: $[message]"
admin:
  - 2704804982
  - 1802732019
  - 1665807109
  - 65504318
  - 2276283971
  - 2076911801
  - 3589711038
  - 752779588
recall:
  enable: true
  mute:
    # 单位: 次数
    value: 3
    # 单位: 秒
    time: 120
  text:
    # 英文请用小写
    - "习大大"
    - "习近平"
    - "毛泽东"
    - "邓小平"
    - "马克思"
    - "社会主义"
    - "主席"
    - "党"
    - "政治"
    - "中国"
    - "中共"
    - "共产"
    - "台湾"
    - "起义"
    - "压迫"
    - "自由"
    - "独裁"
    - "人大"
    - "北京"
    - "天安门"
    - "统治"
    - "反抗"
    - "复辟"
    - "帝制"
    - "袁世凯"
    - "专制"
    - "翻墙"
    - "vpn"
    - "gfw"
    - "言论"
    - "人权"
    - "小熊维尼"
    - "维尼熊"
