ver: 3
prefix:
  - "!"
  - "！"
BotID: 2139645544
GroupID: 1138627074
gnc: true
NumMessage:
  1: "正在独自遨游世界"
  2: "正在体验二人世界"
noWhiteKick: |-
  &6米&f客
  &7----------
  &f你还没有白名单呢
  &f加入我们的QQ群1138627074并发送
  &6!bind %verify%
  来申请白名单
  &f10分钟后过期
  &7----------
