name: OceanBot
version: '${version}'
main: org.encinet.oceanbot.OceanBot
api-version: 1.19
authors: [ Aeolic, ObcbO ]
description: Minecraft with QQ
website: https://github.com/encinet/OceanBot
depend: [MiraiMC]
softdepend: [Vault]
commands:
  oc:
    description: MainCommand
  sign:
    description: Sign
permissions:
  oc.admin:
    description: OnlyAdmin
    default: op