name: Build
on: 
  workflow_dispatch:
jobs:
  gradle:
   runs-on: ubuntu-latest
   steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 17

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2

    - name: Execute Gradle build
      run: |
       chmod 777 ./gradlew
       ./gradlew build

    - name: Upload Jar
      uses: actions/upload-artifact@v3
      with:
          name: OceanBot
          path: build/libs/
