name: Build
on: [pull_request, push, workflow_dispatch]
permissions:
  contents: read
jobs:
  gradle:
   strategy:
     matrix:
       java: [
         17,    # Current Java LTS & minimum supported by Minecraft
       ]
       os: [ubuntu-latest]
   runs-on: ${{ matrix.os }}
   steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        java-version: ${{ matrix.java }}
        distribution: 'zulu'
        cache: 'gradle'
    - name: make gradle wrapper executable
      if: ${{ runner.os != 'Windows' }}
      run: chmod +x ./gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: Upload Jar
      uses: actions/upload-artifact@v3
      with:
          name: OceanBot
          path: build/libs/
